USE QUEIMAS_BANCO;

CREATE TABLE CLIENTE (
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CPF CHAR(11) NOT NULL UNIQUE,
    TELEFONE VARCHAR(15),
    CONSTRAINT CLIENTE_PK PRIMARY KEY (ID_CLIENTE)
);

create table TIPO (
	ID_TIPO INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(255) NOT NULL,
	 CONSTRAINT TIPO_PK PRIMARY KEY (ID_TIPO)
	);

CREATE TABLE PECA (
    ID_PECA INT NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    ID_TIPO INT NOT NULL,
    TAMANHO VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(50),
    ESTAGIO VARCHAR(50) NOT NULL,
    VALOR_TOTAL DECIMAL(5 , 2),
    CONSTRAINT PECA_PK PRIMARY KEY (ID_PECA),
    CONSTRAINT CLIENTE_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
    CONSTRAINT TIPO_FK FOREIGN KEY (ID_TIPO) REFERENCES TIPO (ID_TIPO)
);

CREATE TABLE QUEIMA (
    ID_QUEIMA INT NOT NULL AUTO_INCREMENT,
    DATA_QUEIMA DATE NOT NULL,
    TIPO_QUEIMA VARCHAR(50) NOT NULL,
    TEMPERATURA_ALCANCADA INT NOT NULL,
    ID_PECA INT NOT NULL,
    FORNO VARCHAR(50) NOT NULL,
    PRECO_QUEIMA DECIMAL(5, 2) NOT NULL,
    PAGO BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT QUEIMA_PK PRIMARY KEY (ID_QUEIMA),
    CONSTRAINT PECA_FK FOREIGN KEY (ID_PECA) REFERENCES PECA (ID_PECA)
);

CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ID_SESSAO VARCHAR(255) NOT NULL
);