INSERT INTO CLIENTE (NOME, CPF, TELEFONE) VALUES ('João Silva', '12345678901', '(11) 91234-5678');
INSERT INTO CLIENTE (NOME, CPF, TELEFONE) VALUES ('Maria Oliveira', '23456789012', '(21) 92345-6789');
INSERT INTO CLIENTE (NOME, CPF, TELEFONE) VALUES ('Carlos Souza', '34567890123', '(31) 93456-7890');
INSERT INTO CLIENTE (NOME, CPF, TELEFONE) VALUES ('Ana Costa', '45678901234', '(41) 94567-8901');
INSERT INTO CLIENTE (NOME, CPF, TELEFONE) VALUES ('Paulo Mendes', '56789012345', '(51) 95678-9012');

INSERT INTO TIPO (NOME) VALUES ('Prato');
INSERT INTO TIPO (NOME) VALUES ('Caneca');
INSERT INTO TIPO (NOME) VALUES ('Vaso');
INSERT INTO TIPO (NOME) VALUES ('Tigela');
INSERT INTO TIPO (NOME) VALUES ('Escultura');

-- Inserir registros na tabela PECA
INSERT INTO PECA (ID_CLIENTE, ID_TIPO, TAMANHO, DESCRICAO, ESTAGIO, VALOR_TOTAL) 
VALUES (1, 1, 'PP', 'Prato extra pequeno', 'CRUA', 10.00);

INSERT INTO PECA (ID_CLIENTE, ID_TIPO, TAMANHO, DESCRICAO, ESTAGIO, VALOR_TOTAL) 
VALUES (2, 2, 'P', 'Caneca pequena', 'BISCOITADA', 20.00);

INSERT INTO PECA (ID_CLIENTE, ID_TIPO, TAMANHO, DESCRICAO, ESTAGIO, VALOR_TOTAL) 
VALUES (3, 3, 'M', 'Vaso médio', 'ESMALTADA', 30.00);

INSERT INTO PECA (ID_CLIENTE, ID_TIPO, TAMANHO, DESCRICAO, ESTAGIO, VALOR_TOTAL) 
VALUES (4, 4, 'G', 'Tigela grande', 'CRUA', 40.00);

INSERT INTO PECA (ID_CLIENTE, ID_TIPO, TAMANHO, DESCRICAO, ESTAGIO, VALOR_TOTAL) 
VALUES (5, 5, 'GG', 'Escultura extra grande', 'BISCOITADA', 50.00);


INSERT INTO QUEIMA (DATA_QUEIMA, TIPO_QUEIMA, TEMPERATURA_ALCANCADA, ID_PECA, FORNO, PRECO_QUEIMA) 
VALUES ('2024-01-01', 'BISCOITO', 800, 1, 'Forno A', 15.00);

INSERT INTO QUEIMA (DATA_QUEIMA, TIPO_QUEIMA, TEMPERATURA_ALCANCADA, ID_PECA, FORNO, PRECO_QUEIMA, PAGO) 
VALUES ('2024-01-02', 'ESMALTE', 900, 2, 'Forno B', 20.00, TRUE);

INSERT INTO QUEIMA (DATA_QUEIMA, TIPO_QUEIMA, TEMPERATURA_ALCANCADA, ID_PECA, FORNO, PRECO_QUEIMA, PAGO) 
VALUES ('2024-01-03', 'BISCOITO', 850, 3, 'Forno C', 25.00, FALSE);

INSERT INTO QUEIMA (DATA_QUEIMA, TIPO_QUEIMA, TEMPERATURA_ALCANCADA, ID_PECA, FORNO, PRECO_QUEIMA, PAGO) 
VALUES ('2024-01-04', 'ESMALTE', 950, 4, 'Forno D', 30.00, TRUE);

INSERT INTO QUEIMA (DATA_QUEIMA, TIPO_QUEIMA, TEMPERATURA_ALCANCADA, ID_PECA, FORNO, PRECO_QUEIMA) 
VALUES ('2024-01-05', 'BISCOITO', 870, 5, 'Forno E', 35.00);

INSERT INTO USUARIO (USERNAME, PASSWORD, ID_SESSAO) VALUES
('vic', 'zelda', ''),
('tati', 'mauru', ''),
('malu', 'malu', '');